version: '3.8'
services:
  db:
    image: postgres:15  # 사용할 PostgreSQL 버전
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: hwyeom      # PostgreSQL 사용자
      POSTGRES_PASSWORD: dlatl$00  # PostgreSQL 비밀번호
      POSTGRES_DB: postgres    # 생성할 기본 데이터베이스 이름
    ports:
      - "15432:5432"  # 호스트와 컨테이너 간의 포트 매핑
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/postgresql/data  # 데이터 볼륨 매핑
    networks:
      - hw-network

  app:
    image: hwyeom/dex-rss:latest
    container_name: dex-rss-app
    restart: always
    environment:
      ENV-DB-URL: jdbc:postgresql://db:5432/postgres
      ENV-DB-USER: hwyeom
      ENV-DB-PW: dlatl$00
    ports:
      - "18080:8080"
    networks:
      - hw-network

volumes:
  db_data:

networks:
  hw-network:
    driver: bridge  # 기본 브리지 네트워크 사용