###
POST http://localhost:8080/api/rss/v1/magnet/find
Content-Type: application/json

{
    "url": "https://torrentrj%d.com",
    "path" : "/v-2-13",
    "category" : "drama"
}

### docker
POST http://localhost:8888/api/rss/v1/magnet/find

{
    "url": "https://torrentrj%d.com",
    "path" : "/v-2-13",
    "category" : "drama"
}